spring.application.name=auth-service
server.port=8081

spring.datasource.url=${AUTH_DB_URL:jdbc:mysql://localhost:3306/quantitymeasurement_auth}
spring.datasource.username=${AUTH_DB_USERNAME:root}
spring.datasource.password=${AUTH_DB_PASSWORD:MySql@123}
spring.datasource.driver-class-name=${AUTH_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

springdoc.api-docs.path=/api-docs

management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always

logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG

jwt.secret=${JWT_SECRET:9f8d7c6b5a4e3d2c1b0a9f8d7c6b5a4e1234567890abcdef1234567890abcdef}
jwt.expiration=${JWT_EXPIRATION:86400000}

spring.security.oauth2.client.registration.google.client-id=828943948509-r3urv9oarmg9vuct15i34oodph5j60p3.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
app.oauth2.redirect-uri=${AUTH_OAUTH_REDIRECT_URI:http://localhost:8080/api/v1/auth/oauth2/success}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:false}
eureka.instance.instance-id=${spring.application.name}:${server.port}
