spring.application.name=quantity-measurement-app

spring.datasource.url=jdbc:h2:mem:quantitymeasurementdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=MySql@123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.path=/api-docs

management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always

logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG