spring.application.name=quantity-measurement-app

# ========== MySQL Configuration ==========
spring.datasource.url=jdbc:mysql://localhost:3306/quantitymeasurementapp
spring.datasource.username=root
spring.datasource.password=MySql@123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ========== JPA ==========
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.sql.init.mode=never

# ========== Swagger ==========
springdoc.api-docs.path=/api-docs

# ========== Actuator ==========
management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always

# ========== Logging ==========
logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

# ========== JWT Configuration ==========
jwt.secret=9f8d7c6b5a4e3d2c1b0a9f8d7c6b5a4e1234567890abcdef1234567890abcdef
jwt.expiration=86400000

# ========== Google OAuth2 Configuration ==========
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile



# OAuth2 redirect URI after successful authentication
app.oauth2.redirect-uri=http://localhost:8080/api/v1/auth/oauth2/success
