spring.application.name=quantity-service
server.port=8082

spring.datasource.url=${QUANTITY_DB_URL:jdbc:mysql://localhost:3306/quantitymeasurement_quantity}
spring.datasource.username=${QUANTITY_DB_USERNAME:root}
spring.datasource.password=${QUANTITY_DB_PASSWORD:MySql@123}
spring.datasource.driver-class-name=${QUANTITY_DB_DRIVER:com.mysql.cj.jdbc.Driver}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.sql.init.mode=never

springdoc.api-docs.path=/api-docs

management.endpoints.web.exposure.include=health,metrics,info
management.endpoint.health.show-details=always

logging.level.com.app.quantitymeasurement=DEBUG
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG

jwt.secret=${JWT_SECRET:9f8d7c6b5a4e3d2c1b0a9f8d7c6b5a4e1234567890abcdef1234567890abcdef}

eureka.client.service-url.defaultZone=${EUREKA_SERVER_URL:http://localhost:8761/eureka}
eureka.instance.hostname=${EUREKA_INSTANCE_HOSTNAME:localhost}
eureka.instance.prefer-ip-address=${EUREKA_PREFER_IP:false}
eureka.instance.instance-id=${spring.application.name}:${server.port}
